# Generated by Django 3.1.7 on 2021-08-03 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('developerid', models.CharField(blank=True, max_length=200, null=True)),
                ('apps', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MarketApk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=300, null=True)),
                ('apk', models.CharField(max_length=300)),
                ('installs', models.CharField(blank=True, max_length=100, null=True)),
                ('score', models.CharField(blank=True, default='0', max_length=100, null=True)),
                ('ratings', models.CharField(blank=True, max_length=100, null=True)),
                ('reviews', models.CharField(blank=True, max_length=100, null=True)),
                ('developer', models.CharField(blank=True, max_length=200, null=True)),
                ('developerid', models.CharField(blank=True, max_length=200, null=True)),
                ('developerEmail', models.CharField(blank=True, max_length=100, null=True)),
                ('developerWebsite', models.CharField(blank=True, max_length=300, null=True)),
                ('genre', models.CharField(blank=True, max_length=100, null=True)),
                ('contentRating', models.CharField(blank=True, max_length=100, null=True)),
                ('released', models.CharField(blank=True, max_length=100, null=True)),
                ('updated', models.CharField(blank=True, max_length=100, null=True)),
                ('url', models.CharField(blank=True, max_length=600, null=True)),
            ],
        ),
    ]
