# Generated by Django 3.1.7 on 2021-08-10 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketapk',
            name='name',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
