# Generated by Django 3.1.7 on 2021-08-13 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apkreview',
            name='content',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='apkreview',
            name='replyContent',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
