# Generated by Django 3.1.7 on 2021-08-10 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_marketapk_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marketapk',
            name='name',
        ),
    ]
