# Generated by Django 3.1.7 on 2021-08-10 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0004_auto_20210810_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketapk',
            name='screenshots',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
