# Generated by Django 3.1.7 on 2021-08-10 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0005_auto_20210810_1701'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApkReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(blank=True, max_length=300, null=True)),
                ('userImage', models.CharField(blank=True, max_length=300, null=True)),
                ('content', models.CharField(blank=True, max_length=1000, null=True)),
                ('score', models.IntegerField(blank=True, max_length=5, null=True)),
                ('thumbsUpCount', models.IntegerField(blank=True, max_length=5, null=True)),
                ('reviewCreatedVersion', models.CharField(blank=True, max_length=1000, null=True)),
                ('at', models.DateTimeField(blank=True, null=True)),
                ('replyContent', models.CharField(blank=True, max_length=1000, null=True)),
                ('repliedAt', models.DateTimeField(blank=True, null=True)),
                ('reviewId', models.CharField(blank=True, max_length=1000, null=True)),
                ('apk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.marketapk')),
            ],
        ),
    ]
