# Generated by Django 3.1.7 on 2021-08-10 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0006_apkreview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apkreview',
            name='score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='apkreview',
            name='thumbsUpCount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
